{- Project Euler
Problem 44
==========


   Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first
   ten pentagonal numbers are:

                  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

   It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
   difference, 70 − 22 = 48, is not pentagonal.

   Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
   and difference are pentagonal and D = |P[k] − P[j]| is minimised; what is
   the value of D?


   Answer: 2c2556cb85621309ca647465ffa62370
-}

import           Control.Monad
import           Data.Maybe

maybeSquare x
  | root^2 == x    = Just root
  | otherwise      = Nothing
  where
    root = floor $ sqrt $ fromIntegral x

maybeDiv x y
  | y == 0              = Nothing
  | 0 == mod x y        = Just (quot x y)
  | otherwise           = Nothing

process :: Integer -> Integer -> Maybe Integer
process i d = do
  let pi = pentagonal i
  j <- maybeDiv ((-) pi (pentagonal d)) (3 * d)
  let pl = j * (j * 3 - 1) + pi
  x0 <- maybeSquare $ 1 + 24*pl
  let l = maybeDiv (1 + x0) 6
  case l of
    Just l'  -> Just pi
    Nothing -> Nothing

pentagonal :: Integer -> Integer
pentagonal n = quot (n * (3 * n -1)) 2

attempt i d = msum [process i d' | d' <- [d, d+3..i-3]]

main :: IO ()
main = print $ fromJust $ msum [attempt i (mod i 3) | i <- [8..]]
