name: bazel-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      id: bazel-cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel-tmp

    - name: Mount download cache
      id: bin
      uses: actions/cache@v1
      with:
        path: "/home/runner/bin"
        key: downloads-bin

    - name: Install misc
      run: |
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive
        sudo -E apt-get -y install --no-install-recommends \
          python python3 libgmp-dev npm clang-11 make libncurses5 \
          libblas-dev liblapack-dev python3-pip

    - name: Install bazelisk
      if: steps.bin.outputs.cache-hit != 'true'
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p ~/bin/
        mv bazelisk-linux-amd64 ~/bin/bazel
        chmod +x ~/bin/bazel

    - name: test
      run: |
        cd "${GITHUB_WORKSPACE}"
        ~/bin/bazel test -t- pain:all
      env:
        USE_BAZEL_VERSION: 2.1.0

  document:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python_deps
      run: |
        python3 -m pip install wheel mkdocs mkdocs-material python-markdown-math requests
    - name: track_image
      run: |
        cd "${GITHUB_WORKSPACE}"
        mkdir docs
        ln -s `pwd`/README.md docs/index.md
        ~/bin/bazel test -t- pain:all | grep PASSED | scripts/gen_svg.py | tee docs/progress.svg
        python3 -m mkdocs build
      env:
        USE_BAZEL_VERSION: 2.1.0
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        ssh-key: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: site
