name: bazel-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      id: bazel-cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel-tmp

    - name: Mount download cache
      id: bin
      uses: actions/cache@v1
      with:
        path: "/home/runner/bin"
        key: downloads-bin

    - name: Install misc
      run: |
        apt-get update && export DEBIAN_FRONTEND=noninteractive \
          && apt-get -y install --no-install-recommends \
          python python3 libgmp-dev npm clang-11 make libncurses5 \
          libblas-dev liblapack-dev

    - name: Install bazelisk
      if: steps.bin.outputs.cache-hit != 'true'
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p ~/bin/
        mv bazelisk-linux-amd64 ~/bin/bazel
        chmod +x ~/bin/bazel

    - name: test
      run: |
        cd "${GITHUB_WORKSPACE}"
        ~/bin/bazel test -t- pain:all